language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
cache:
- bundler
script:
- RAILS_ENV=test bundle exec rake db:test:prepare --trace
- bundle exec rspec
deploy:
  provider: heroku
  api_key: ...
  app: tranquil-garden-76939
  run: rails db:migrate
  on:
    branch: main
